name: ci-pipeline

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run Flask App
              run: |
                python app.py
                sleep 10

            - name: Validate Application
              run: curl http://127.0.0.1:5000
